# Generated by Django 5.0.2 on 2024-03-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LookupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('abuse_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cname_record', models.JSONField(blank=True, null=True)),
                ('a_record', models.JSONField(blank=True, default=dict, null=True)),
                ('mx_record', models.JSONField(blank=True, null=True)),
                ('ns_record', models.JSONField(blank=True, null=True)),
                ('soa_record', models.JSONField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
