# Generated by Django 5.0.2 on 2024-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deviceHub', '0002_alter_device_location_alter_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=50)),
                ('vlan_id', models.PositiveIntegerField()),
                ('devices', models.ManyToManyField(to='deviceHub.device')),
            ],
        ),
    ]
