# Generated by Django 5.0.2 on 2024-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_name', models.CharField(max_length=100)),
                ('smtp_sender', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(max_length=100)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_server_port', models.IntegerField()),
            ],
        ),
    ]
