# Generated by Django 5.0.2 on 2024-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BGPCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_number', models.CharField(max_length=255)),
                ('as_name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
