# Generated by Django 5.0.2 on 2024-02-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='rack_loc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
